services:
  ml-classification:
    build: .
    container_name: raman-ml
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # For GUI display (matplotlib plots)
    environment:
      - DISPLAY=${DISPLAY:-:99}
      - MPLBACKEND=Agg  # Use non-interactive backend for saving plots
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
